script = "finetune-ldm-color-palette.py" # not used for now
[wandb]
mode = "online" # "online", "offline", "disabled"
entity = "piercus"
project = "histo-autoencoder"
name = "32-64"
tags = ["autoencoder"]

[histogram_auto_encoder]
latent_dim = 64
resnet_sizes = [32, 32, 32, 32, 32, 32, 32]
n_down_samples = 6
color_bits = 6

[models]
histogram_auto_encoder = {train = true}

[training]
duration = "1:epoch"
seed = 0
gpu_index = 1
batch_size = 8
gradient_accumulation = "1:step"
clip_grad_norm = 1.0
# clip_grad_value = 1.0
evaluation_interval = "50:step"
evaluation_seed = 1
num_workers = 8

[optimizer]
optimizer = "AdamW" # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
learning_rate = 5e-3
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[scheduler]
scheduler_type = "ConstantLR"
update_interval = "1:step"

[dropout]
dropout_probability = 0.2
use_gyro_dropout = false

[dataset]
hf_repo = "1aurent/unsplash-lite-palette"
revision = "main"
resize_image_max_size = 512
caption_key = "ai_description"
split = "train[10:]"

[eval_dataset]
hf_repo = "1aurent/unsplash-lite-palette"
revision = "main"
resize_image_max_size = 512
caption_key = "ai_description"
split = "train[:10]"

[checkpointing]
save_interval = "100:step"
use_wandb = true
