script = "finetune-ldm-color-palette.py" # not used for now
[wandb]
mode = "offline" # "online", "offline", "disabled"
entity = "piercus"
project = "color-palette"
name = "mlp-weighted"
tags = ["local", "reload-ckpt", "grid-eval", "weighted"]

[models]
unet = {checkpoint = "tests/weights/stable-diffusion-1-5/unet.safetensors", gpu_index=1, train = false}
text_encoder = {checkpoint = "tests/weights/stable-diffusion-1-5/CLIPTextEncoderL.safetensors", gpu_index=0, train = false}
lda = {checkpoint = "tests/weights/stable-diffusion-1-5/lda.safetensors", gpu_index=0, train = false}
color_palette_encoder = {gpu_index=1, train = true}

[adapters]
color_palette_adapter = {checkpoint = "./tmp/converted-mlp-step4998.safetensors"}

[latent_diffusion]
unconditional_sampling_probability = 0.1
offset_noise = 0.2

[color_palette]
max_colors = 8
feedforward_dim = 20
num_layers = 2
mode = 'mlp'
embedding_dim = 10
weighted_palette = true

[training]
duration = "2000:step"
seed = 0
batch_size = 1
gradient_accumulation = "1:step"
clip_grad_norm = 1.0
# clip_grad_value = 1.0
evaluation_interval = "1000:step"
evaluation_seed = 1

[optimizer]
optimizer = "AdamW" # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
learning_rate = 1e-4
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[scheduler]
scheduler_type = "ConstantLR"
update_interval = "1:step"
warmup = "500:step"

[dropout]
dropout_probability = 0.0
use_gyro_dropout = false

[dataset]
hf_repo = "1aurent/unsplash-lite-palette"
revision = "main"
resize_image_max_size = 512
caption_key = "ai_description"
split = "train"

[checkpointing]
save_interval = "10000:step"
use_wandb = true

[eval_dataset]
hf_repo = "1aurent/unsplash-lite-palette"
revision = "main"
resize_image_max_size = 512
caption_key = "ai_description"
split = "train[0:4]"

[evaluation]
batch_size = 3
num_inference_steps = 30
use_short_prompts = false
db_indexes = [0, 1, 2, 3]
prompts = [
     "A Bustling City Street",
     "A cute cat",
     "An oil painting",
     "A photography of a beautiful woman"
]
condition_scale = 7.5
