script = "finetune-ldm-color-palette.py" # not used for now
[wandb]
mode = "disabled" # "online", "offline", "disabled"
entity = "piercus"
project = "color-palette"
name = "test-save-ckpts"
[models]
unet = {checkpoint = "tests/weights/stable-diffusion-1-5/unet.safetensors", gpu_index=1, train = false}
text_encoder = {checkpoint = "tests/weights/stable-diffusion-1-5/CLIPTextEncoderL.safetensors", gpu_index=0, train = false}
lda = {checkpoint = "tests/weights/stable-diffusion-1-5/lda.safetensors", gpu_index=0, train = false}
color_palette_encoder = {gpu_index=1, train = true}

[adapters]
color_palette_adapter = {checkpoint= "ckpts/dummy-44ah5rn1/step100.safetensors"}

[latent_diffusion]
unconditional_sampling_probability = 0.1
offset_noise = 0.1

[color_palette]
max_colors = 8
feedforward_dim = 20
num_layers = 2
num_attention_heads = 2
embedding_dim = 10

[training]
duration = "300:step"
seed = 0
gpu_index = 0
batch_size = 1
gradient_accumulation = "1:step"
clip_grad_norm = 1.0
# clip_grad_value = 1.0
evaluation_interval = "1000:step"
evaluation_seed = 1

[optimizer]
optimizer = "AdamW" # "SGD", "Adam", "AdamW", "AdamW8bit", "Lion8bit"
learning_rate = 5e-4
betas = [0.9, 0.999]
eps = 1e-8
weight_decay = 1e-2

[scheduler]
scheduler_type = "ConstantLR"
update_interval = "1:step"
warmup = "500:step"

[dropout]
dropout_probability = 0.2
use_gyro_dropout = false

[dataset]
hf_repo = "1aurent/unsplash-lite-palette"
revision = "main"
resize_image_max_size = 512
caption_key = "ai_description"
split = "train"

[checkpointing]
save_interval = "100:step"
use_wandb = true

[test_color_palette]
num_inference_steps = 30
use_short_prompts = false
prompts = [
        {"text" = "a cute cat", "color_palette" = [[0,0,255]], seed=1},
        {"text" = "a cute cat", "color_palette" = [[255,0,0]], seed=1},
#        {"text" = "a cute cat", "color_palette" = [[0,0,255], [255,255,255], [255,0,0]]},
#        {"text" = "a cute cat", "color_palette" = [[255,0,0], [255,255,255], [0,0,255]]}
]
num_palette_sample = 1 # 8
condition_scale = 7.5
