name: CI

on: push

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
          cache-prefix: 'refiners-rye-cache'

      - name: add home shims dir to PATH
        run: echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: pin python
        run: rye pin 3.10

      - name: rye sync
        run: rye sync --all-features

      - name: ruff format
        run: rye run ruff format --check .

      - name: ruff check
        run: rye run ruff check .

      - name: typecheck
        run: rye run pyright
